# Generated by Django 3.1.2 on 2020-10-12 15:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_startpage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'bold', 'italic', 'link', 'align_center', 'align_right', 'strikethrough'])), ('HTML', wagtail.core.blocks.RawHTMLBlock()), ('Embedded', wagtail.embeds.blocks.EmbedBlock()), ('Picture', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
