# Generated by Django 3.1.2 on 2020-10-13 15:25

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201012_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='greeting',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
